LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

$(call import-add-path,$(LOCAL_PATH)/../../cocos2d)
$(call import-add-path,$(LOCAL_PATH)/../../cocos2d/external)
$(call import-add-path,$(LOCAL_PATH)/../../cocos2d/cocos)

LOCAL_MODULE := cocos2dcpp_shared

LOCAL_MODULE_FILENAME := libcocos2dcpp

LOCAL_CPPFLAGS += -DGUID_ANDROID=1

LOCAL_SRC_FILES := hellocpp/main.cpp \
                   ../../Classes/AppDelegate.cpp \
				   ../../Classes/AddLineToBoardBottomSpell.cpp \
				   ../../Classes/AddLineToBoardBottomSpellDelegate.cpp \
				   ../../Classes/AddLineToBoardSpellAnimationController.cpp \
				   ../../Classes/AIMovementStrategy.cpp \
				   ../../Classes/AISpellCastsStrategy.cpp \
				   ../../Classes/AnimationSynchonizer.cpp \
				   ../../Classes/BackButtonController.cpp \
				   ../../Classes/BossEnvironmentFactory.cpp \
				   ../../Classes/BossInterface.cpp \
				   ../../Classes/BossMovementAnimationController.cpp \
				   ../../Classes/BossMovementDelegate.cpp \
				   ../../Classes/BossMovementObserver.cpp \
				   ../../Classes/BossWithOneTetraminoDelegate.cpp \
				   ../../Classes/ChainFromTetraminosChecker.cpp \
				   ../../Classes/CocosNodesHelper.cpp \
				   ../../Classes/CocosViewConfigurator.cpp \
				   ../../Classes/CohesionSpell.cpp \
				   ../../Classes/CohesionSpellAnimationController.cpp \
				   ../../Classes/CohesionSpellDelegate.cpp \
				   ../../Classes/CollisionDelegate.cpp \
				   ../../Classes/CurrentDetailAccelerationDelegate.cpp \
				   ../../Classes/CurrentDetailController.cpp \
				   ../../Classes/CurrentDetailDataSource.cpp \
				   ../../Classes/CurrentDetailExplosionFactory.cpp \
				   ../../Classes/CurrentDetailTetraminosChecker.cpp \
				   ../../Classes/CurrentLevelDataSource.cpp \
				   ../../Classes/CurrentPlayerDataSource.cpp \
				   ../../Classes/CurrentPlayerSerializer.cpp \
				   ../../Classes/CurrentPlayerSpellsDelegate.cpp \
				   ../../Classes/CurrentVictoryConditionDataSource.cpp \
				   ../../Classes/DamageToPlayerSpell.cpp \
				   ../../Classes/DetailForTutorialController.cpp \
				   ../../Classes/DetailsFromBoardDataSource.cpp \
				   ../../Classes/DetailViewDataSource.cpp \
				   ../../Classes/DevelopersSceneFactory.cpp \
				   ../../Classes/EndGameMenuElementCreator.cpp \
				   ../../Classes/EndGameMenuElementsCollectionCreator.cpp \
				   ../../Classes/EndGameMenuElementsFactory.cpp \
				   ../../Classes/ExplosionAnimationController.cpp \
				   ../../Classes/ExplosionAnimationDelegate.cpp \
				   ../../Classes/ExplosionsForTutorialController.cpp \
				   ../../Classes/FallenDetailAnimationController.cpp \
				   ../../Classes/FallenDetailAnimationDelegate.cpp \
				   ../../Classes/FallenDetailAnimationFactory.cpp \
				   ../../Classes/FallenDetailDelegate.cpp \
				   ../../Classes/FightWithBossLevelTutorial.cpp \
				   ../../Classes/FillingGapInBoardSystem.cpp \
				   ../../Classes/FinalSceneAnimationController.cpp \
				   ../../Classes/FinalSceneBackgroundController.cpp \
				   ../../Classes/FinalSceneFactory.cpp \
				   ../../Classes/FirestormSpellAnimationController.cpp       \
				   ../../Classes/FirestormSpellDelegate.cpp                  \
				   ../../Classes/FirestromSpell.cpp                          \
				   ../../Classes/FirestromSpellExplosionPositionDelegate.cpp \
				   ../../Classes/FullLineCombination.cpp                     \
				   ../../Classes/GameAnalyticController.cpp                  \
				   ../../Classes/GameAnalyticControllerDelegate.cpp          \
				   ../../Classes/GameBackgroundSoundRegulator.cpp            \
				   ../../Classes/GameBoard.cpp                               \
				   ../../Classes/GameBoardController.cpp                     \
				   ../../Classes/GameBoardViewDataSource.cpp                 \
				   ../../Classes/GameDataLoader.cpp                          \
				   ../../Classes/GameElementsDataHelper.cpp                  \
				   ../../Classes/GameFileExtensionMaker.cpp                  \
				   ../../Classes/GameFlowSystem.cpp                          \
				   ../../Classes/GameGraphicsDataSource.cpp                  \
				   ../../Classes/GameGraphicsLoader.cpp                      \
				   ../../Classes/GameHelper.cpp                              \
				   ../../Classes/GameHudsController.cpp                      \
				   ../../Classes/GameInitiator.cpp                           \
				   ../../Classes/GameKeyWithSuffixSupporter.cpp              \
				   ../../Classes/GameLevelsAttributesCreator.cpp             \
				   ../../Classes/GameLevelsDataFactory.cpp                   \
				   ../../Classes/GameLevelsDataSource.cpp                    \
				   ../../Classes/GameLevelsMenuDataSource.cpp                \
				   ../../Classes/GameLocalizationDataSource.cpp              \
				   ../../Classes/GameLogicLoader.cpp                         \
				   ../../Classes/GamePlayersDatabase.cpp                     \
				   ../../Classes/GamePlayersDatabaseSerializer.cpp           \
				   ../../Classes/GamePopUpsController.cpp                    \
				   ../../Classes/GameRecordsFishesController.cpp             \
				   ../../Classes/GameRecordsSceneFactory.cpp                 \
				   ../../Classes/GameResultDelegate.cpp                      \
				   ../../Classes/GamesDevelopersAnimationController.cpp      \
				   ../../Classes/GamesDevelopersBoardController.cpp          \
				   ../../Classes/GameSoundController.cpp                     \
				   ../../Classes/GameSoundEffectsRegulator.cpp               \
				   ../../Classes/GameSoundLoader.cpp                         \
				   ../../Classes/GamesRecordsAnimationController.cpp         \
				   ../../Classes/GamesRecordsBoardController.cpp             \
				   ../../Classes/GameStatesHelper.cpp                        \
				   ../../Classes/GameSystemInterface.cpp                     \
				   ../../Classes/GameTimeStepController.cpp                  \
				   ../../Classes/GameTransitionsViewController.cpp           \
				   ../../Classes/GameTutorial.cpp                            \
				   ../../Classes/GameTutorialBeaverTalkController.cpp        \
				   ../../Classes/GameTutorialController.cpp                  \
				   ../../Classes/GameTutorialOrderController.cpp             \
				   ../../Classes/GameTutorialsAnimationController.cpp        \
				   ../../Classes/GameTutorialsFactory.cpp                    \
				   ../../Classes/GameTutorialShowLevelIcon.cpp               \
				   ../../Classes/GameTutorialWithOneStep.cpp                 \
				   ../../Classes/GameViewElementsDataSource.cpp              \
				   ../../Classes/GameViewInformationFactory.cpp              \
				   ../../Classes/GameViewStyleHelper.cpp                     \
				   ../../Classes/GameWorldAnimationController.cpp            \
				   ../../Classes/GameWorldBackgroundController.cpp           \
				   ../../Classes/GameWorldController.cpp                     \
				   ../../Classes/GATrackerpp.cpp                             \
				   ../../Classes/GoogleAnalyticIndicatorsDataSource.cpp      \
				   ../../Classes/guid.cpp                                    \
				   ../../Classes/HorisontalChainChecker.cpp                  \
				   ../../Classes/KeysForEnumsDataSource.cpp                  \
				   ../../Classes/KingBoss.cpp                                \
				   ../../Classes/LoadGameController.cpp                      \
				   ../../Classes/LoadingGameDataSource.cpp                   \
				   ../../Classes/LoadingGameSceneFactory.cpp                 \
				   ../../Classes/LoadingGameWaveController.cpp               \
				   ../../Classes/MainGameBackgroundDataSource.cpp            \
				   ../../Classes/MainGameEndPopUp.cpp                        \
				   ../../Classes/MainGameEndPopUpSoundController.cpp         \
				   ../../Classes/MainGamePauseDelegate.cpp                   \
				   ../../Classes/MainGamePauseEndObserver.cpp                \
				   ../../Classes/MainGamePausePopUp.cpp                      \
				   ../../Classes/MainGamePauseViewController.cpp             \
				   ../../Classes/MainGamePlayerScoreController.cpp           \
				   ../../Classes/MainGameSceneFactory.cpp                    \
				   ../../Classes/MainGameVictoryConditionController.cpp      \
				   ../../Classes/MouseOverMenuItem.cpp                       \
				   ../../Classes/NewTetraminoDetailDataSource.cpp            \
				   ../../Classes/PlaceSomeDetailsCondition.cpp               \
				   ../../Classes/PlayerActionControllerDesktop.cpp           \
				   ../../Classes/PlayerActionControllerFactory.cpp           \
				   ../../Classes/PlayerActionsForTutorialController.cpp      \
				   ../../Classes/PlayerCreatorController.cpp                 \
				   ../../Classes/PlayerGameControlsDataSource.cpp            \
				   ../../Classes/PlayerScoreForTutorialController.cpp        \
				   ../../Classes/PlayerSpellsControllerDesktop.cpp           \
				   ../../Classes/PlayerSpellsControllerFactory.cpp           \
				   ../../Classes/PlayerStatusDataSource.cpp                  \
				   ../../Classes/PlayerStatusDelegateInterface.cpp           \
				   ../../Classes/PrincessBoss.cpp                            \
				   ../../Classes/pugiconfig.hpp                              \
				   ../../Classes/pugixml.cpp                                 \
				   ../../Classes/pugixml.hpp                                 \
				   ../../Classes/QueenBoss.cpp                               \
				   ../../Classes/RandomExplosionsSpell.cpp                   \
				   ../../Classes/RegulateSoundPopUp.cpp                      \
				   ../../Classes/RemainSomeTimeCondition.cpp                 \
				   ../../Classes/RemoveSomeTetraminosCondition.cpp           \
				   ../../Classes/ResourcesLoader.cpp                         \
				   ../../Classes/RocketSpell.cpp                             \
				   ../../Classes/RocketSpellAnimationController.cpp          \
				   ../../Classes/RocketSpellDelegate.cpp                     \
				   ../../Classes/SceneFactory.cpp                            \
				   ../../Classes/ScenesFactory.cpp                           \
				   ../../Classes/ScenesTransitionsFactory.cpp                \
				   ../../Classes/ScreenPopUp.cpp                             \
				   ../../Classes/SelectGameLevelBackgroundController.cpp     \
				   ../../Classes/SelectGameLevelBeaverOnRaftController.cpp   \
				   ../../Classes/SelectGameLevelBeaverTalkController.cpp     \
				   ../../Classes/SelectGameLevelController.cpp               \
				   ../../Classes/SelectGameLevelSceneFactory.cpp             \
				   ../../Classes/SelectLevelPlayerStatusController.cpp       \
				   ../../Classes/ServiceInterface.cpp                        \
				   ../../Classes/ServiceLocator.cpp                          \
				   ../../Classes/SimilarTetraminosCombination.cpp            \
				   ../../Classes/SpellBox.cpp                                \
				   ../../Classes/SpellInterface.cpp                          \
				   ../../Classes/SpellRechargeDelegate.cpp                   \
				   ../../Classes/SpellRechargeSystem.cpp                     \
				   ../../Classes/SpellsViewDataSource.cpp                    \
				   ../../Classes/StartGameAnimationController.cpp            \
				   ../../Classes/StartGameBackgroundController.cpp           \
				   ../../Classes/StartGameBeaverController.cpp               \
				   ../../Classes/StartGameFishesController.cpp               \
				   ../../Classes/StartGameMenuController.cpp                 \
				   ../../Classes/StartGameMenuDataSource.cpp                 \
				   ../../Classes/StartGameSceneFactory.cpp                   \
				   ../../Classes/StartLevelGameTutorial.cpp                  \
				   ../../Classes/StartMainGamePlayerScoreDataSource.cpp      \
				   ../../Classes/StringsSupporter.cpp                        \
				   ../../Classes/TetraminisDetailsFactory.cpp                \
				   ../../Classes/Tetramino.cpp                               \
				   ../../Classes/TetraminoColorsDataSource.cpp               \
				   ../../Classes/TetraminoDetail.cpp                         \
				   ../../Classes/TetraminoDetailLocatorDelegate.cpp          \
				   ../../Classes/TetraminoExplosionFactory.cpp               \
				   ../../Classes/TetraminoObserverInterface.cpp              \
				   ../../Classes/TetraminoRemovingObserverInterface.cpp      \
				   ../../Classes/TetraminosAppearanceAnimationFactory.cpp    \
				   ../../Classes/TetraminosChainCleaner.cpp                  \
				   ../../Classes/TetraminosCombinatorDelegate.cpp            \
				   ../../Classes/TetraminosFactory.cpp                       \
				   ../../Classes/TetraminosFallEvent.cpp                     \
				   ../../Classes/TetraminosForTutorialController.cpp         \
				   ../../Classes/TetraminosInGameBoardViewDataSource.cpp     \
				   ../../Classes/TetraminosPositionsDelegate.cpp             \
				   ../../Classes/TetraminoViewController.cpp                 \
				   ../../Classes/TetrisLogicSystem.cpp                       \
				   ../../Classes/TimeAccelerationEvent.cpp                   \
				   ../../Classes/VerticalChainChecker.cpp                    \
				   ../../Classes/VictoryConditionForTutorialController.cpp   \
				   ../../Classes/VictoryConditionInterface.cpp               \
				   ../../Classes/VictoryConditionViewDataSource.cpp          \
				   ../../Classes/WinBossCondition.cpp                        \
				   ../../Classes/WinGameSystem.cpp                           

LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../Classes \
					$(LOCAL_PATH)/../../cocos2d/external/curl/include/android/curl \
					$(LOCAL_PATH)/../../cocos2d/cocos/ui \
					$(LOCAL_PATH)/../../../..

# _COCOS_HEADER_ANDROID_BEGIN
# _COCOS_HEADER_ANDROID_END


LOCAL_STATIC_LIBRARIES := cocos2dx_static

# _COCOS_LIB_ANDROID_BEGIN
# _COCOS_LIB_ANDROID_END

include $(BUILD_SHARED_LIBRARY)

$(call import-module,.)

# _COCOS_LIB_IMPORT_ANDROID_BEGIN
# _COCOS_LIB_IMPORT_ANDROID_END
