

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "OpenGLESPage.xaml.h"




void ::cocos2d::OpenGLESPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///OpenGLESPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///OpenGLESPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the SwapChainPanel named 'swapChainPanel'
    swapChainPanel = safe_cast<::Windows::UI::Xaml::Controls::SwapChainPanel^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"swapChainPanel"));
    // Get the Button named 'cocos2d_editbox'
    cocos2d_editbox = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cocos2d_editbox"));
    // Get the Flyout named 'cocos2d_editbox_flyout'
    cocos2d_editbox_flyout = safe_cast<::Windows::UI::Xaml::Controls::Flyout^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cocos2d_editbox_flyout"));
    // Get the Grid named 'cocos2d_editbox_grid'
    cocos2d_editbox_grid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cocos2d_editbox_grid"));
    // Get the Button named 'cocos2d_editbox_done'
    cocos2d_editbox_done = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cocos2d_editbox_done"));
    // Get the Button named 'cocos2d_editbox_cancel'
    cocos2d_editbox_cancel = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"cocos2d_editbox_cancel"));
}

void ::cocos2d::OpenGLESPage::Connect(int connectionId, Platform::Object^ target)
{
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

